version: '3.8'
services:
  scheduler-api:
    image: python:3.9-slim
    working_dir: /app
    command: |
      bash -c "
        pip install --no-cache-dir -r requirements.txt &&
        python scheduler_api.py
      "
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONPATH=/app
    depends_on:
      - redis
    networks:
      - network_swarm_public
    volumes:
      - type: bind
        source: .
        target: /app
        
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - network_swarm_public
      
volumes:
  redis_data:
  
networks:
  network_swarm_public:
    name: network_swarm_public
    external: true
