version: '3.8'
services:
  scheduler-api:
    image: python:3.9
    command: |
      bash -c "
        git clone https://github.com/IvanAires23/scheduler.git /app &&
        cd /app &&
        pip install --no-cache-dir -r requirements.txt &&
        python scheduler_api.py
      "
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONPATH=/app
    depends_on:
      - redis
    deploy:
      replicas: 1
      
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    deploy:
      replicas: 1
      
volumes:
  redis_data:
